### PR TITLE
Add Typescript definition file

### PR DESCRIPTION
**Pull request by frankhale**
I'm new to creating Typescript definition files but am using this one for youtube-search in my own app. I think it's working well. I wanted to get it out there for a wider audience and see if there is any more improvements that can be made to it. 

Thank you for this great module! I've been using it for a long time. Happy New Year to you!!!

### CODE REVIEW

**Comment by MaxGfeller** [comment]
I have to say i don't know too much about TypeScript, but looks good to me! Thanks for that.

Want to update the README too?

**Comment by frankhale** [comment]
Sure I'll update the README as well

**Comment by frankhale** [comment]
README has been updated to explain TypeScript usage

**Comment by frankhale** [comment]
Are the README updates okay?

**Comment by frankhale** [comment]
I can go either way, I can remove it or keep it. I suppose the info doesn't hurt and I've seen similar on other projects before.

**Comment by MaxGfeller** [comment]
Alright, let's keep it in then :) thanks for the PR, merged in 1.0.8

**Pull request merged**
