### PR TITLE
Add Promise Support

### LINKED ISSUE #31: Promise support
Does this library support promises? If not, it'd be a great feature to add!

### PR DESCRIPTION
**Pull request by FireController1847**
Simple enough-or I thought. Fixes #31

### CODE REVIEW

**Comment by FireController1847** [comment]
Don't know why the test is failing. Didn't add any module requirements.

**Comment by FireController1847** [comment]
@MaxGfeller Any status on getting this pushed?

**Comment by FireController1847** [comment]
Closing because promises have been implemented.

**Comment by MaxGfeller** [comment]
Sorry for not replying @FireController1847. I'd love to merge this actually. Could you [squash](https://gist.github.com/patik/b8a9dc5cd356f9f6f980) your commits into one?

**Comment by FireController1847** [comment]
Can't your PR this in by selecting "Squash and Merge"? Sorry, I've never squashed my commits before :p

**Comment by FireController1847** [comment]
Oh I see you linked to a tutorial. I will as soon as I get the chance (if I can remember).

**Comment by FireController1847** [comment]
Due to the fact that I deleted the patch-1 branch a while back, I'm going to have to make a seperate PR.

**Pull request closed without merging**
