### PR TITLE
Add Promise Support (2)

### LINKED ISSUE #31: Promise support
Does this library support promises? If not, it'd be a great feature to add!

### PR DESCRIPTION
**Pull request by FireController1847**
Reference #32. Fixes #31.

### CODE REVIEW

**Comment by FireController1847** [comment]
There we go! I did it.

**Comment by FireController1847** [comment]
OMG IT ADDED A SECOND ONE. I HATE GITHUB!!!

**Comment by MaxGfeller** [comment]
Thanks!

**Comment by FireController1847** [comment]
No problem!

**Comment by MaxGfeller** [comment]
I fixed a small issue when opts were not passed and added a test case. It's now published as `1.1.0`.

**Comment by FireController1847** [comment]
Okie! :)

**Pull request merged**
